main: awzaw\megaban\Main
api: [2.0.0]
load: STARTUP

name: MegaBan
description: ban players using multiple vectors
version: 1.2.1
author: awzaw
website: https://github.com/Awzaw/MegaBan

commands:
  megaban:
    description: MegaBan a player
    usage: "/megaban <player> [options]"
    permission: megaban
    aliases: [mban]
  megaunban:
    description: Pardon a MegaBanned player
    usage: "/megaunban <player> AND YOU MUST pardon, pardonip, pardoncid manually"
    permission: megaban
    aliases: [megapardon, mpardon]
permissions:
  megaban:
    default: op
    description: "MegaBan"